# Change these first
owner: JeronimoTaber # Your GitHub organization or username, where this repository lives
repo: upptimeMapp # The name of this repository

sites:
  #- name: Mapp Jornales
  #  url: https://jornales.mapp.com.ar/
  #- name: Masturismo
  #  url: https://masturismo.mapp.com.ar/
  #- name: Mapp Ondemand
  #  url: https://ondemand.mapp.com.ar/
  #- name: Mapp Consorcios
  #  url: https://consorcios.mapp.com.ar/
  #- name: Mapp Aventura
  #  url: https://aventura.mapp.com.ar/
  - name: Mapp
    url: https://www.mapp.com.ar/upptime.html
  - name: La Mercantil API
    url: https://api.mercantilandina.com.ar/
    expectedStatusCodes:
     - 200
     - 401
     - 404
  - name: COEX
    url: https://www.coex.com.ar/upptime.html

assignees: # Users to assign downtime issues (optional)
  - pabloaguiar
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptimeMapp
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
